import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-government-grant-indirect-cost-recovery",
  "engine": "recovery",
  "title": "Government Grant Indirect Cost Recovery",
  "shortTitle": "Government Grant Indirect Cost Recovery",
  "tagline": "Recover allowable indirect costs through correct rate bases, exclusions, carryforwards, and retroactive adjustments.",
  "industry": "Grant Finance",
  "buyer": "Universities, nonprofits, and government contractors",
  "uiPort": 4690,
  "apiPort": 5690,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Government Grant Indirect Cost Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements in one accountable workflow. Recover allowable indirect costs through correct rate bases, exclusions, carryforwards, and retroactive adjustments.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Government Grant Indirect Cost Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("award-agreement-library","GGI01","Award agreement library","Execute award agreement library using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed award agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Award agreement library Reference","text","GGI01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("indirect-rate-agreement","GGI02","Indirect rate agreement","Execute indirect rate agreement using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed indirect rate agreement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Indirect rate agreement Reference","text","GGI02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("direct-cost-ingestion","GGI03","Direct cost ingestion","Execute direct cost ingestion using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed direct cost ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Direct cost ingestion Reference","text","GGI03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("modified-total-direct-cost-base","GGI04","Modified total direct cost base","Execute modified total direct cost base using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed modified total direct cost base decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Modified total direct cost base Reference","text","GGI04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("capital-expenditure-exclusion","GGI05","Capital expenditure exclusion","Execute capital expenditure exclusion using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed capital expenditure exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Capital expenditure exclusion Reference","text","GGI05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("subaward-threshold-exclusion","GGI06","Subaward threshold exclusion","Execute subaward threshold exclusion using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed subaward threshold exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Subaward threshold exclusion Reference","text","GGI06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("participant-support-exclusion","GGI07","Participant support exclusion","Execute participant support exclusion using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed participant support exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Participant support exclusion Reference","text","GGI07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("indirect-cost-calculation","GGI08","Indirect cost calculation","Execute indirect cost calculation using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed indirect cost calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Indirect cost calculation Reference","text","GGI08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("provisional-to-final-adjustment","GGI09","Provisional-to-final adjustment","Execute provisional-to-final adjustment using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed provisional-to-final adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Provisional-to-final adjustment Reference","text","GGI09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("carryforward-calculation","GGI10","Carryforward calculation","Execute carryforward calculation using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed carryforward calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Carryforward calculation Reference","text","GGI10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("award-ceiling-control","GGI11","Award ceiling control","Execute award ceiling control using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed award ceiling control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Award ceiling control Reference","text","GGI11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("drawdown-reconciliation","GGI12","Drawdown reconciliation","Execute drawdown reconciliation using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed drawdown reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Drawdown reconciliation Reference","text","GGI12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("sponsor-adjustment-request","GGI13","Sponsor adjustment request","Execute sponsor adjustment request using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed sponsor adjustment request decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Sponsor adjustment request Reference","text","GGI13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("cash-recovery-tracking","GGI14","Cash recovery tracking","Execute cash recovery tracking using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed cash recovery tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Cash recovery tracking Reference","text","GGI14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]}),
feature("award-rate-analytics","GGI15","Award rate analytics","Execute award rate analytics using grant agreements, approved rates, direct costs, cost pools, exclusions, subawards, drawdowns, invoices, rate adjustments, and reimbursements.","Produce a governed award rate analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Recipient / Award","text","Recipient / Award · Standard Case"],["caseReference","Award rate analytics Reference","text","GGI15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1153750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1396038],["domainDriver","Rate Type","select","Provisional",["Provisional","Final","De minimis"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Award agreement library case","Indirect rate agreement case","Direct cost ingestion case","Modified total direct cost base case","Capital expenditure exclusion case"]})
]);
